const blogs = [
  {
    blogName: 'First Blog',
    blogAbstract:
      'React, JavaScript, DOM manipulation, HTML5, React router, ES6-ES9, Redux, AJAX, jQuery',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id donec ultrices. In massa tempor nec feugiat nisl pretium fusce id. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Tristique nulla aliquet enim tortor at auctor urna. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Est ante in nibh mauris cursus mattis molestie a iaculis. Diam donec adipiscing tristique risus nec feugiat in fermentum. Mus mauris vitae ultricies leo integer malesuada nunc vel. Rutrum quisque non tellus orci ac auctor augue. Aliquet enim tortor at auctor urna nunc id. Porttitor rhoncus dolor purus non. Nibh sit amet commodo nulla facilisi nullam vehicula. Enim ut sem viverra aliquet eget sit amet tellus. Est velit egestas dui id ornare arcu odio ut. Pulvinar sapien et ligula ullamcorper malesuada. Risus nec feugiat in fermentum posuere urna nec tincidunt. Lectus proin nibh nisl condimentum id venenatis a condimentum. Nulla porttitor massa id neque aliquam. Ullamcorper sit amet risus nullam eget felis eget. Ultrices vitae auctor eu augue. Habitant morbi tristique senectus et netus et malesuada. Viverra tellus in hac habitasse platea dictumst vestibulum. Vestibulum sed arcu non odio euismod. Vel risus commodo viverra maecenas accumsan lacus. Sed felis eget velit aliquet sagittis id consectetur purus. Integer vitae justo eget magna. Ultrices eros in cursus turpis. Semper auctor neque vitae tempus quam pellentesque nec. Elit pellentesque habitant morbi tristique. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sapien eget mi proin sed libero enim sed. Tincidunt arcu non sodales neque sodales ut. Ut consequat semper viverra nam libero justo laoreet. Augue interdum velit euismod in pellentesque massa. Neque vitae tempus quam pellentesque nec nam. Sed arcu non odio euismod lacinia. Morbi tincidunt augue interdum velit euismod in. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Leo duis ut diam quam. Suscipit adipiscing bibendum est ultricies integer quis. Ultrices gravida dictum fusce ut placerat orci. Risus quis varius quam quisque id diam vel quam. Arcu non odio euismod lacinia at quis risus sed. Massa massa ultricies mi quis hendrerit dolor magna eget.',
  },
  {
    blogName: 'Second Blog',
    blogAbstract:
      'React, JavaScript, DOM manipulation, HTML5, React router, ES6-ES9, Redux, AJAX, jQuery',
    description:
      'Ipsun Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id donec ultrices. In massa tempor nec feugiat nisl pretium fusce id. Fringilla urna porttitor rhoncus dolor purus non enim praesent elementum. Tristique nulla aliquet enim tortor at auctor urna. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Est ante in nibh mauris cursus mattis molestie a iaculis. Diam donec adipiscing tristique risus nec feugiat in fermentum. Mus mauris vitae ultricies leo integer malesuada nunc vel. Rutrum quisque non tellus orci ac auctor augue. Aliquet enim tortor at auctor urna nunc id. Porttitor rhoncus dolor purus non. Nibh sit amet commodo nulla facilisi nullam vehicula. Enim ut sem viverra aliquet eget sit amet tellus. Est velit egestas dui id ornare arcu odio ut. Pulvinar sapien et ligula ullamcorper malesuada. Risus nec feugiat in fermentum posuere urna nec tincidunt. Lectus proin nibh nisl condimentum id venenatis a condimentum. Nulla porttitor massa id neque aliquam. Ullamcorper sit amet risus nullam eget felis eget. Ultrices vitae auctor eu augue. Habitant morbi tristique senectus et netus et malesuada. Viverra tellus in hac habitasse platea dictumst vestibulum. Vestibulum sed arcu non odio euismod. Vel risus commodo viverra maecenas accumsan lacus. Sed felis eget velit aliquet sagittis id consectetur purus. Integer vitae justo eget magna. Ultrices eros in cursus turpis. Semper auctor neque vitae tempus quam pellentesque nec. Elit pellentesque habitant morbi tristique. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sapien eget mi proin sed libero enim sed. Tincidunt arcu non sodales neque sodales ut. Ut consequat semper viverra nam libero justo laoreet. Augue interdum velit euismod in pellentesque massa. Neque vitae tempus quam pellentesque nec nam. Sed arcu non odio euismod lacinia. Morbi tincidunt augue interdum velit euismod in. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Leo duis ut diam quam. Suscipit adipiscing bibendum est ultricies integer quis. Ultrices gravida dictum fusce ut placerat orci. Risus quis varius quam quisque id diam vel quam. Arcu non odio euismod lacinia at quis risus sed. Massa massa ultricies mi quis hendrerit dolor magna eget.',
  },
];

export default blogs;
